# Generated by Django 5.1.6 on 2025-02-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_name", models.CharField(max_length=255, unique=True)),
                ("parent_id", models.PositiveIntegerField(blank=True, default=0)),
                ("is_client_usable", models.BooleanField(blank=True, default=False)),
                (
                    "category_icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/categories"
                    ),
                ),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Category",
                "db_table": "category",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="category_id_db0083_idx"),
                    models.Index(
                        fields=["category_name"], name="category_categor_d484be_idx"
                    ),
                    models.Index(
                        fields=["is_client_usable"], name="category_is_clie_3b0174_idx"
                    ),
                    models.Index(
                        fields=["active_status"], name="category_active__543f22_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attribute_name", models.CharField(max_length=255, unique=True)),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Product Unit Attribute",
                "verbose_name_plural": "Product Unit Attribute",
                "db_table": "product_unit_attribute",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="product_uni_id_fc1ca2_idx"),
                    models.Index(
                        fields=["attribute_name"], name="product_uni_attribu_7da1e2_idx"
                    ),
                    models.Index(
                        fields=["active_status"], name="product_uni_active__0a9f06_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sub_category_name", models.CharField(max_length=255, unique=True)),
                ("parent_id", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "sub_category_icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/sub_categories"
                    ),
                ),
                ("is_client_usable", models.BooleanField(blank=True, default=False)),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_category_category",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Category",
                "verbose_name_plural": "Sub-Category",
                "db_table": "sub_category",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="sub_categor_id_650cec_idx"),
                    models.Index(
                        fields=["sub_category_name"],
                        name="sub_categor_sub_cat_4dd523_idx",
                    ),
                    models.Index(
                        fields=["is_client_usable"],
                        name="sub_categor_is_clie_86acc2_idx",
                    ),
                    models.Index(
                        fields=["active_status"], name="sub_categor_active__f6abd7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitAttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unit_value", models.CharField(max_length=255)),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "unit_attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unit_attributes",
                        to="products.unitattribute",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Unit Value",
                "verbose_name_plural": "Product Unit Value",
                "db_table": "product_unit_value",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="product_uni_id_b1146f_idx"),
                    models.Index(
                        fields=["unit_value"], name="product_uni_unit_va_3d9589_idx"
                    ),
                    models.Index(
                        fields=["active_status"], name="product_uni_active__7d8f1b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit_attribute", "unit_value"),
                        name="unique_unit_value",
                    )
                ],
            },
        ),
    ]
