# Generated by Django 5.1.6 on 2025-02-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_name", models.CharField(max_length=255, unique=True)),
                ("parent_id", models.PositiveIntegerField(blank=True, default=0)),
                ("is_client_usable", models.BooleanField(blank=True, default=False)),
                (
                    "category_icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/categories"
                    ),
                ),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Category",
                "db_table": "category",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="category_id_db0083_idx"),
                    models.Index(
                        fields=["category_name"], name="category_categor_d484be_idx"
                    ),
                    models.Index(
                        fields=["is_client_usable"], name="category_is_clie_3b0174_idx"
                    ),
                    models.Index(
                        fields=["active_status"], name="category_active__543f22_idx"
                    ),
                ],
            },
        ),
    ]
