# Generated by Django 5.1.6 on 2025-02-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unitattribute",
            options={
                "ordering": ["-id"],
                "verbose_name": "Unit Attribute",
                "verbose_name_plural": "Unit Attribute",
            },
        ),
        migrations.AlterModelOptions(
            name="unitattributevalue",
            options={
                "ordering": ["-id"],
                "verbose_name": "Unit Attribute Value",
                "verbose_name_plural": "Unit Attribute Value",
            },
        ),
        migrations.RenameIndex(
            model_name="unitattribute",
            new_name="unit_attrib_id_7f300d_idx",
            old_name="product_uni_id_fc1ca2_idx",
        ),
        migrations.RenameIndex(
            model_name="unitattribute",
            new_name="unit_attrib_attribu_dfc910_idx",
            old_name="product_uni_attribu_7da1e2_idx",
        ),
        migrations.RenameIndex(
            model_name="unitattribute",
            new_name="unit_attrib_active__db0e49_idx",
            old_name="product_uni_active__0a9f06_idx",
        ),
        migrations.RenameIndex(
            model_name="unitattributevalue",
            new_name="unit_attrib_id_501de3_idx",
            old_name="product_uni_id_b1146f_idx",
        ),
        migrations.RenameIndex(
            model_name="unitattributevalue",
            new_name="unit_attrib_unit_va_f7f3f2_idx",
            old_name="product_uni_unit_va_3d9589_idx",
        ),
        migrations.RenameIndex(
            model_name="unitattributevalue",
            new_name="unit_attrib_active__5002cf_idx",
            old_name="product_uni_active__7d8f1b_idx",
        ),
        migrations.AlterModelTable(
            name="unitattribute",
            table="unit_attribute",
        ),
        migrations.AlterModelTable(
            name="unitattributevalue",
            table="unit_attribute_value",
        ),
    ]
