# Generated by Django 5.1.6 on 2025-02-21 09:32

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_unitattribute_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("brand_name", models.CharField(max_length=255, unique=True)),
                (
                    "origin_country",
                    models.CharField(
                        blank=True, default="Bangladesh", max_length=100, null=True
                    ),
                ),
                (
                    "brand_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="product/brands"
                    ),
                ),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                (
                    "brand_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brand",
                "db_table": "brand",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="brand_id_2f0614_idx"),
                    models.Index(
                        fields=["brand_name"], name="brand_brand_n_0502cf_idx"
                    ),
                    models.Index(
                        fields=["origin_country"], name="brand_origin__d7a221_idx"
                    ),
                    models.Index(
                        fields=["active_status"], name="brand_active__c82066_idx"
                    ),
                ],
            },
        ),
    ]
