# Generated by Django 5.1.6 on 2025-02-21 17:32

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_brand"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManufacturerProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_category", models.CharField(max_length=255, unique=True)),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Manufacturer Product Category",
                "verbose_name_plural": "Manufacturer Product Category",
                "db_table": "manufacturer_products_category",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="manufacture_id_67cdfc_idx"),
                    models.Index(
                        fields=["product_category"],
                        name="manufacture_product_6a95ca_idx",
                    ),
                    models.Index(
                        fields=["active_status"], name="manufacture_active__7d52fe_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("manufacturer_name", models.CharField(max_length=255, unique=True)),
                (
                    "manufacturer_logo",
                    models.ImageField(blank=True, null=True, upload_to="manufacturer/"),
                ),
                (
                    "contact_person",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "manufacturer_email",
                    models.EmailField(blank=True, max_length=255, null=True),
                ),
                (
                    "manufacturer_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, null=True, region=None
                    ),
                ),
                ("manufacturer_address", models.TextField(blank=True, null=True)),
                (
                    "manufacturer_category",
                    models.CharField(
                        blank=True,
                        choices=[("local", "Local"), ("foreign", "Foreign")],
                        default="local",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "product_category",
                    models.ManyToManyField(
                        related_name="manufacturer_product_category",
                        to="products.manufacturerproductcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturer",
                "db_table": "manufacturer",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="manufacture_id_6771ee_idx"),
                    models.Index(
                        fields=["manufacturer_name"],
                        name="manufacture_manufac_01b007_idx",
                    ),
                    models.Index(
                        fields=["manufacturer_email"],
                        name="manufacture_manufac_371549_idx",
                    ),
                    models.Index(
                        fields=["manufacturer_phone"],
                        name="manufacture_manufac_519f3d_idx",
                    ),
                    models.Index(
                        fields=["active_status"], name="manufacture_active__8d52f8_idx"
                    ),
                ],
            },
        ),
    ]
