# Generated by Django 5.1.6 on 2025-02-21 18:16

import apps.common.functions.validator.numaric_validator
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_manufacturerproductcategory_manufacturer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vat_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        default=Decimal("0.00"),
                        max_digits=19,
                        null=True,
                        unique=True,
                        validators=[
                            apps.common.functions.validator.numaric_validator.min_decimal_value
                        ],
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("percentage", "Percentage"),
                            ("flat_rate", "Flat Rate"),
                        ],
                        default="percentage",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "VAT",
                "verbose_name_plural": "VAT",
                "db_table": "vat",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="vat_id_3a9f01_idx"),
                    models.Index(fields=["value_type"], name="vat_value_t_482a00_idx"),
                    models.Index(
                        fields=["active_status"], name="vat_active__594cb8_idx"
                    ),
                ],
            },
        ),
    ]
