# Generated by Django 5.1.6 on 2025-02-22 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductImageGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("product_image", models.ImageField(upload_to="product/")),
                (
                    "image_alt_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("image_seo_tags", models.TextField(blank=True, null=True)),
                ("image_meta_tags", models.TextField(blank=True, null=True)),
                ("image_meta_description", models.TextField(blank=True, null=True)),
                ("image_seo_description", models.TextField(blank=True, null=True)),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product Image Gallery",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_image_gallery",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image Gallery",
                "verbose_name_plural": "Product Image Gallery",
                "db_table": "product_image_gallery",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="product_ima_id_0a74a4_idx"),
                    models.Index(
                        fields=["product_id"], name="product_ima_product_e5be17_idx"
                    ),
                    models.Index(
                        fields=["active_status"], name="product_ima_active__2dca36_idx"
                    ),
                ],
            },
        ),
    ]
