# Generated by Django 5.1.6 on 2025-02-22 15:46

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_productimagegallery"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSeo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seo_title", models.CharField(max_length=255, unique=True)),
                ("meta_tags", models.TextField(blank=True, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("seo_description", models.TextField(blank=True, null=True)),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_seo",
                        to="products.product",
                    ),
                ),
                (
                    "seo_keyword",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="seo_keyword",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product SEO",
                "verbose_name_plural": "Product SEO",
                "db_table": "product_seo",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="product_seo_id_5bca72_idx"),
                    models.Index(
                        fields=["product_id"], name="product_seo_product_4929a9_idx"
                    ),
                    models.Index(
                        fields=["active_status"], name="product_seo_active__e5ca15_idx"
                    ),
                ],
            },
        ),
    ]
