# Generated by Django 5.1.6 on 2025-02-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_variationattribute_variationattributevalue"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variation_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "variation_image",
                    models.ImageField(blank=True, null=True, upload_to="product/"),
                ),
                (
                    "image_alt_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "active_status",
                    models.CharField(
                        blank=True,
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variation_product",
                        to="products.product",
                    ),
                ),
                (
                    "variation_attribute",
                    models.ManyToManyField(
                        related_name="product_variation_attribute",
                        to="products.variationattributevalue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Variation",
                "verbose_name_plural": "Product Variations",
                "db_table": "product_variation",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="product_var_id_7b812b_idx"),
                    models.Index(
                        fields=["variation_name"], name="product_var_variati_73abca_idx"
                    ),
                    models.Index(
                        fields=["active_status"], name="product_var_active__58ca87_idx"
                    ),
                ],
            },
        ),
    ]
