# Generated by Django 5.1.6 on 2025-02-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_productvariation"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="web_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
