# Generated by Django 5.1.6 on 2025-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenericNameInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("generic_name", models.CharField(max_length=250, unique=True)),
                (
                    "drug_category",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "chemical_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "chemical_formula",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "formula_image",
                    models.ImageField(blank=True, null=True, upload_to="generic_name/"),
                ),
                (
                    "active_ingredients",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "brand_equivalents",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "active_status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Generic Name Information",
                "verbose_name_plural": "Generic Name Information",
                "db_table": "generic_name_information",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["id"], name="generic_nam_id_21ce4c_idx"),
                    models.Index(
                        fields=["generic_name"], name="generic_nam_generic_683e4a_idx"
                    ),
                    models.Index(
                        fields=["active_status"], name="generic_nam_active__39a8d9_idx"
                    ),
                ],
            },
        ),
    ]
